/**
 * DB 컬럼 설명 매핑 파일
 *
 * 이 파일은 데이터베이스의 모든 테이블과 컬럼에 대한 한국어 설명을 정의합니다.
 * DB 뷰어(/admin/database) 페이지에서 툴팁으로 표시됩니다.
 *
 * [구조]
 *   DB_DESCRIPTIONS = {
 *     테이블명: {
 *       _table: '테이블 전체 설명',
 *       컬럼명: '컬럼 설명 (타입, FK 관계, 사용처 등)',
 *     }
 *   }
 *
 * [업데이트 방법]
 *   - 새 테이블 추가 시: DB_DESCRIPTIONS에 테이블명 키를 추가하고 _table + 컬럼 설명 작성
 *   - 새 컬럼 추가 시: 해당 테이블 객체에 컬럼명: '설명' 추가
 *   - _table 키는 테이블 수준 설명에 사용되는 예약 키입니다 (실제 컬럼명으로 사용 불가)
 *
 * [참고]
 *   - 설명은 간결하게 작성 (1~2문장)
 *   - FK 관계가 있으면 '(테이블명.컬럼명 FK)' 형태로 표기
 *   - CASCADE/SET NULL 등 삭제 동작도 함께 표기
 *   - 데이터 타입이 특수한 경우 괄호 안에 명시 (예: JSONB, TEXT[], UUID)
 */

const DB_DESCRIPTIONS = {
  users: {
    _table: '사용자 계정 정보. 로그인, SSO 인증, 권한 관리에 사용',
    id: '사용자 고유 식별자 (UUID). 모든 사용자 관련 테이블에서 FK로 참조',
    email: '로그인 이메일 주소 (UNIQUE). 로컬/SSO 인증 시 식별자로 사용',
    password_hash: '비밀번호 해시 (bcrypt). SSO 사용자는 NULL 가능',
    name: '사용자 이름. 채팅, 게시판, 공지사항 등에서 표시',
    department: '부서명. SSO 동기화 시 자동 업데이트',
    cell: '연락처 (휴대전화)',
    role: '사용자 권한 (user/admin/manager). 관리자 페이지 접근 제어에 사용',
    last_login_at: '마지막 로그인 시각. 보안 감사 및 비활성 계정 감지',
    created_at: '계정 생성 시각',
    updated_at: '계정 정보 최종 수정 시각',
    employee_no: '사원번호 (UNIQUE). SSO 연동 시 사용자 식별 키',
    employee_id: '직원 ID. SSO 시스템 내부 식별자',
    sso_user_id: 'SSO 시스템의 userId',
    company_code: '그룹사 코드',
    company_name: '그룹사명',
    company_id: '그룹사 ID',
    department_id: '부서 ID (SSO)',
    department_no: '부서 번호 (SSO)',
    department_location: '부서 위치 경로 (SSO)',
    employee_position_name: '직급 (SSO)',
    employee_class: '직원 유형/분류 (SSO)',
    employee_security_level: '보안 등급 (정수). SSO 기반 접근 제어',
    lang: '사용자 언어 설정. 기본값: ko',
    login_deny_yn: '로그인 거부 여부 (Y/N). SSO 기반',
    auth_type: '인증 타입 (local/sso). 로그인 방식 구분',
    auth_result: '마지막 인증 결과 (SUCCESS 등)',
    auth_result_message: '인증 결과 상세 메시지',
    auth_event_id: '인증 이벤트 ID (SSO 추적용)',
    sso_result_code: 'SSO 응답 코드 (200 등)',
    sso_response_datetime: 'SSO 응답 시각',
    sso_transaction_id: 'SSO 트랜잭션 ID',
    last_active_at: '마지막 실제 활동 시각. 세션 만료 판단에 사용',
  },
  chat_rooms: {
    _table: '채팅방 정보. 사용자별 대화 세션 관리',
    id: '채팅방 고유 ID (UUID)',
    user_id: '채팅방 소유자 (users.id FK). CASCADE 삭제',
    name: '채팅방 이름. AI가 자동 생성하거나 사용자가 수정',
    message_count: '채팅방 내 메시지 수. 통계 및 UI 표시용',
    created_at: '채팅방 생성 시각',
    updated_at: '채팅방 최종 수정 시각',
  },
  chat_history: {
    _table: '채팅 메시지 이력. 사용자-AI 간 대화 내용 저장',
    id: '메시지 고유 ID (UUID)',
    room_id: '소속 채팅방 (chat_rooms.id FK). CASCADE 삭제',
    user_id: '메시지 작성자 (users.id FK). 삭제 시 NULL',
    role: '메시지 역할 (user/assistant). 사용자 질문 vs AI 응답 구분',
    text: '메시지 본문 텍스트',
    model: '응답 생성에 사용된 AI 모델명',
    file_references: '첨부 파일 참조 정보 (JSONB)',
    feedback: '사용자 피드백 (좋아요/싫어요 등)',
    created_at: '메시지 생성 시각',
  },
  messages: {
    _table: '관리자용 메시지 로그. 모든 채팅 메시지의 관리/감사 기록',
    id: '로그 고유 ID (UUID)',
    role: '메시지 역할 (user/assistant)',
    user_role: '메시지 작성자의 권한 (user/admin/manager)',
    model: '사용된 AI 모델명',
    text: '메시지 본문 텍스트',
    room_id: '소속 채팅방 ID',
    user_id: '작성자 (users.id FK)',
    client_ip: '클라이언트 IP 주소. 보안 감사용',
    feedback: '사용자 피드백',
    is_deleted: '소프트 삭제 여부. true면 UI에서 숨김',
    deleted_at: '삭제 시각',
    deleted_by: '삭제 실행자 (관리자 UUID)',
    created_at: '메시지 생성 시각',
  },
  chat_files: {
    _table: '채팅에 첨부된 파일 정보. 업로드/OCR/텍스트 추출 상태 관리',
    id: '파일 고유 ID (UUID)',
    room_id: '소속 채팅방 (chat_rooms.id FK). CASCADE 삭제',
    user_id: '업로더 (users.id FK)',
    file_name: '원본 파일명',
    saved_file_name: '서버 저장 파일명 (UUID 기반)',
    file_size: '파일 크기 (bytes)',
    mime_type: '파일 MIME 타입 (image/png, application/pdf 등)',
    status: '처리 상태 (processing/completed/error/failed)',
    extracted_text: '파일에서 추출된 텍스트 내용',
    extraction_method: '텍스트 추출 방식 (OCR, 파서 등)',
    processed_at: '처리 완료 시각',
    pdf_metadata: 'PDF 메타데이터 (JSONB). 페이지수, 작성자 등',
    ocr_results: 'OCR 처리 결과 상세 (JSONB)',
    ocr_summary: 'OCR 결과 요약 텍스트',
    uploaded_at: '파일 업로드 시각',
  },
  uploaded_files: {
    _table: '업로드된 파일 (레거시). chat_files로 대체됨',
    id: '파일 고유 ID',
    room_id: '소속 채팅방 FK',
    user_id: '업로더 FK',
    file_name: '원본 파일명',
    saved_file_name: '서버 저장 파일명',
    file_size: '파일 크기 (bytes)',
    mime_type: 'MIME 타입',
    status: '처리 상태 (processing/completed/error)',
    extracted_text: '추출된 텍스트',
    uploaded_at: '업로드 시각',
  },
  settings: {
    _table: '시스템 전역 설정. 사이트 설정, 모델 연결, 파일 제한 등',
    id: '설정 고유 ID (UUID)',
    config_type: '설정 유형. 기본값: general',
    multiturn_count: '멀티턴 대화 최대 횟수. 채팅 컨텍스트 유지 범위',
    tooltip_enabled: '모델 선택 툴팁 표시 여부',
    tooltip_message: '모델 선택 시 표시할 툴팁 메시지',
    chat_widget_enabled: '채팅 위젯 (우하단 플로팅) 표시 여부',
    site_title: '사이트 제목. 브라우저 탭/헤더에 표시',
    site_description: '사이트 설명. 메타 태그용',
    favicon_url: '파비콘 URL',
    file_parsing_model: '파일 파싱에 사용할 AI 모델명',
    file_parsing_enabled: '파일 파싱 기능 활성화 여부',
    room_name_generation_model: '채팅방 이름 자동 생성에 사용할 모델',
    max_file_size: '최대 파일 크기 제한 (bytes)',
    max_files_per_room: '채팅방당 최대 파일 수',
    max_total_size_per_room: '채팅방당 총 파일 크기 제한 (bytes)',
    supported_image_formats: '지원 이미지 형식 목록 (JSONB)',
    supported_document_formats: '지원 문서 형식 목록 (JSONB)',
    ollama_endpoints: 'Ollama 서버 엔드포인트 URL 목록',
    endpoint_type: '모델 엔드포인트 타입 (ollama/openai_compat 등)',
    custom_endpoints: '사용자 정의 엔드포인트 목록 (JSONB)',
    openai_compat_base: 'OpenAI 호환 API 베이스 URL',
    openai_compat_api_key: 'OpenAI 호환 API 키',
    created_at: '설정 생성 시각',
    updated_at: '설정 최종 수정 시각',
    max_images_per_message: '메시지당 최대 이미지 첨부 수',
    max_user_question_length: '사용자 질문 최대 글자수 제한',
    image_analysis_model: '이미지 분석에 사용할 AI 모델',
    image_analysis_prompt: '이미지 분석 시 사용할 프롬프트',
    profile_edit_enabled: '사용자 프로필 수정 허용 여부',
    manual_preset_base_url: '수동 프리셋 베이스 URL',
    manual_preset_api_base: '수동 프리셋 API 베이스',
    board_enabled: '게시판 기능 활성화 여부',
    support_contacts: '고객 지원 연락처 목록 (JSONB)',
    support_contacts_enabled: '고객 지원 연락처 표시 여부',
    login_type: '기본 로그인 방식 (local/sso)',
    api_config_example: 'API 설정 예시 텍스트',
    api_curl_example: 'API curl 명령어 예시',
  },
  admin_settings: {
    _table: '관리자 전용 설정 (JSONB). 동적 설정 저장소',
    id: '설정 고유 ID',
    config_type: '설정 유형. 기본값: admin',
    created_at: '생성 시각',
    updated_at: '수정 시각',
    settings: '설정 데이터 (JSONB). 키-값 쌍으로 저장',
  },
  model_config: {
    _table: '모델 설정 (레거시). models/model_categories 테이블로 대체됨',
    id: '설정 고유 ID',
    config_type: '설정 유형. 기본값: model',
    created_at: '생성 시각',
    updated_at: '수정 시각',
    config: '모델 설정 데이터 (JSONB)',
  },
  model_categories: {
    _table: '모델 카테고리 분류. 모델 선택 UI에서 그룹 표시',
    id: '카테고리 고유 ID (UUID)',
    category_key: '카테고리 고유 키 (UNIQUE). 예: general, coding, creative',
    label: '카테고리 표시 이름',
    display_order: '카테고리 정렬 순서. 낮을수록 먼저 표시',
    created_at: '생성 시각',
    updated_at: '수정 시각',
  },
  models: {
    _table: 'AI 모델 정보. 모델 선택, 엔드포인트 연결, 권한 제어',
    id: '모델 고유 ID (UUID)',
    category_id: '소속 카테고리 (model_categories.id FK)',
    model_name: '모델 실제 이름 (API 호출 시 사용)',
    label: '모델 표시 이름 (UI에서 사용자에게 보이는 이름)',
    tooltip: '모델 설명 툴팁 텍스트',
    is_default: '기본 선택 모델 여부',
    admin_only: '관리자 전용 모델 여부',
    system_prompt: '시스템 프롬프트 배열 (TEXT[])',
    endpoint: '모델 서버 엔드포인트 URL',
    display_order: '모델 정렬 순서',
    created_at: '생성 시각',
    updated_at: '수정 시각',
    api_config: 'API 설정 (JSONB). 온도, max_tokens 등',
    api_key: '모델별 API 키',
    visible: '모델 표시 여부. false면 선택 목록에서 숨김',
    multi_turn_limit: '멀티턴 대화 제한 수 (모델별 오버라이드)',
    multi_turn_unlimited: '멀티턴 제한 없음 여부',
  },
  prompt_config: {
    _table: '프롬프트 설정 (JSONB). 시스템 프롬프트 템플릿 관리',
    id: '설정 고유 ID',
    config_type: '설정 유형. 기본값: prompt',
    created_at: '생성 시각',
    updated_at: '수정 시각',
    config: '프롬프트 설정 데이터 (JSONB)',
  },
  model_logs: {
    _table: '모델 API 호출 로그. 성능 모니터링 및 사용량 추적',
    id: '로그 고유 ID (UUID)',
    user_id: '요청자 (users.id FK)',
    instance_id: '서버 인스턴스 ID',
    instance_type: '서버 인스턴스 유형',
    type: '로그 유형 (request, response, error 등)',
    level: '로그 레벨 (info, warn, error)',
    category: '로그 카테고리',
    method: 'HTTP 메서드 (GET, POST 등)',
    endpoint: 'API 엔드포인트 URL',
    model: '사용된 모델명',
    message: '로그 메시지',
    error: '에러 메시지 (에러 발생 시)',
    metadata: '추가 메타데이터 (JSONB)',
    provider: '모델 프로바이더 (ollama, openai 등)',
    client_ip: '클라이언트 IP',
    user_agent: '클라이언트 User-Agent',
    response_time: '응답 소요 시간 (ms)',
    status_code: 'HTTP 상태 코드',
    is_stream: '스트리밍 응답 여부',
    prompt_tokens: '프롬프트 토큰 수',
    completion_tokens: '응답 토큰 수',
    total_tokens: '총 토큰 수',
    has_files: '파일 첨부 여부',
    file_count: '첨부 파일 수',
    timestamp: '로그 기록 시각',
  },
  model_server: {
    _table: '모델 서버 정보. 엔드포인트 등록 및 상태 관리',
    id: '서버 고유 ID (UUID)',
    endpoint: '서버 엔드포인트 URL (UNIQUE)',
    name: '서버 이름 (UNIQUE)',
    status: '서버 상태 (active/inactive 등)',
    created_at: '등록 시각',
    updated_at: '수정 시각',
    metadata: '추가 메타데이터 (JSONB)',
  },
  model_server_error_history: {
    _table: '모델 서버 에러 이력. 헬스체크 실패 기록',
    id: '이력 고유 ID (UUID)',
    endpoint_url: '에러 발생 엔드포인트 URL',
    endpoint_name: '엔드포인트 이름',
    provider: '프로바이더 (ollama, openai 등)',
    error_message: '에러 메시지',
    error_type: '에러 유형 (timeout, connection_refused 등)',
    response_time: '응답 시간 (ms)',
    status: '서버 상태 (unhealthy 등)',
    checked_at: '헬스체크 시각',
    metadata: '추가 정보 (JSONB)',
  },
  model_server_status: {
    _table: '모델 서버 실시간 상태. 하트비트 및 리소스 모니터링',
    id: '상태 고유 ID (UUID)',
    instance_id: '인스턴스 고유 ID (UNIQUE)',
    instance_type: '인스턴스 유형',
    hostname: '호스트명',
    port: '포트 번호',
    pid: '프로세스 ID',
    node_version: 'Node.js 버전',
    environment: '실행 환경 (development/production)',
    last_heartbeat: '마지막 하트비트 시각',
    uptime: '서버 가동 시간 (초)',
    memory_usage: '메모리 사용량 (JSONB)',
    cpu_usage: 'CPU 사용량 (JSONB)',
    created_at: '등록 시각',
    updated_at: '상태 갱신 시각',
  },
  external_api_prompts: {
    _table: '외부 API 프롬프트 저장소. 요청 메시지 원본 보관',
    id: '프롬프트 고유 ID (UUID)',
    prompt: '프롬프트 텍스트',
    messages: '메시지 배열 (JSONB). OpenAI 형식의 대화 컨텍스트',
    created_at: '저장 시각',
  },
  external_api_logs: {
    _table: '외부 API 호출 로그. 외부 시스템/도구에서의 API 사용 기록',
    id: '로그 고유 ID (UUID)',
    api_type: 'API 유형 (chat, completion 등)',
    endpoint: '호출된 엔드포인트 URL',
    model: '사용된 모델명',
    provider: '프로바이더',
    prompt_id: '프롬프트 참조 (external_api_prompts.id FK)',
    prompt: '프롬프트 텍스트 (인라인)',
    messages: '메시지 배열 (JSONB)',
    response_token_count: '응답 토큰 수',
    prompt_token_count: '프롬프트 토큰 수',
    total_token_count: '총 토큰 수',
    response_time: '총 응답 시간 (ms)',
    first_response_time: '첫 응답까지 시간 (ms, 스트리밍)',
    final_response_time: '최종 응답 시간 (ms, 스트리밍)',
    status_code: 'HTTP 상태 코드',
    is_stream: '스트리밍 응답 여부',
    error: '에러 메시지',
    retry_count: '재시도 횟수',
    client_ip: '클라이언트 IP',
    user_agent: 'User-Agent 문자열',
    x_forwarded_for: '프록시 경유 IP (X-Forwarded-For)',
    x_real_ip: '실제 클라이언트 IP (X-Real-IP)',
    x_forwarded_proto: '프로토콜 (http/https)',
    x_forwarded_host: '원래 호스트',
    client_tool: '클라이언트 도구명 (curl, python-requests 등)',
    client_tool_version: '클라이언트 도구 버전',
    operating_system: '클라이언트 OS',
    architecture: '클라이언트 아키텍처 (x86_64 등)',
    accept_language: '요청 Accept-Language 헤더',
    accept_encoding: '요청 Accept-Encoding 헤더',
    accept_charset: '요청 Accept-Charset 헤더',
    referer: 'Referer 헤더',
    origin: 'Origin 헤더',
    authorization: '인증 헤더 (마스킹됨)',
    content_type: 'Content-Type 헤더',
    x_requested_with: 'X-Requested-With 헤더',
    x_client_name: '커스텀 클라이언트 이름 헤더',
    x_client_version: '커스텀 클라이언트 버전 헤더',
    x_user_name: '커스텀 사용자 이름 헤더',
    x_workspace: '커스텀 워크스페이스 헤더',
    user_id: '요청자 (users.id FK)',
    token_hash: 'API 토큰 해시. 토큰 추적용',
    token_name: 'API 토큰 이름',
    request_time: '요청 발생 시각 (클라이언트 측)',
    timezone: '클라이언트 타임존',
    session_hash: '세션 해시. 동일 세션 추적용',
    fingerprint_hash: '브라우저 핑거프린트 해시',
    user_identifier: '사용자 식별자 (커스텀)',
    conversation_id: '대화 ID. 멀티턴 추적용',
    room_id: '연결된 채팅방 ID',
    request_headers: '요청 헤더 전체 (JSONB)',
    request_body: '요청 본문 (JSONB)',
    response_headers: '응답 헤더 (JSONB)',
    response_body: '응답 본문 (JSONB)',
    timestamp: '로그 기록 시각',
    source: '요청 출처 (external_api 등)',
  },
  api_tokens: {
    _table: 'API 인증 토큰. 외부 시스템 API 접근 키 관리',
    id: '토큰 고유 ID (UUID)',
    user_id: '토큰 소유자 (users.id FK). CASCADE 삭제',
    token_hash: '토큰 해시값. 인증 시 비교용',
    encrypted_token: '레거시 호환용 컬럼. 신규 API 토큰은 원본을 저장하지 않음',
    name: '토큰 이름 (구분용)',
    expires_at: '토큰 만료 시각',
    is_active: '토큰 활성화 상태',
    last_used_at: '마지막 사용 시각',
    created_by: '토큰 생성자 (users.id FK)',
    created_at: '토큰 생성 시각',
    updated_at: '토큰 수정 시각',
  },
  notices: {
    _table: '공지사항. 사용자에게 표시할 공지 및 팝업 관리',
    id: '공지 고유 ID (UUID)',
    title: '공지 제목',
    content: '공지 내용 (HTML/텍스트)',
    is_popup: '팝업 공지 여부. true면 로그인 시 팝업 표시',
    is_active: '공지 활성화 여부. false면 목록에서 숨김',
    author_id: '작성자 (users.id FK)',
    author_name: '작성자 이름 (비정규화)',
    views: '조회수',
    created_at: '공지 생성 시각',
    updated_at: '공지 수정 시각',
  },
  user_chats: {
    _table: '사용자-채팅방 연결 테이블. 채팅방 접근 권한 관리',
    id: '레코드 고유 ID (UUID)',
    user_id: '사용자 (users.id FK). CASCADE 삭제',
    room_id: '채팅방 (chat_rooms.id FK). CASCADE 삭제',
    created_at: '연결 생성 시각',
  },
  qa_logs: {
    _table: 'QA 로그. 품질 보증 테스트 기록',
    id: '로그 고유 ID (UUID)',
    timestamp: '로그 기록 시각',
    log_data: '로그 데이터 (JSONB). 테스트 결과, 메트릭 등',
  },
  rag_documents: {
    _table: 'RAG 문서 저장소. 벡터 검색용 문서 관리',
    id: '문서 고유 ID (UUID)',
    file_name: '서버 저장 파일명',
    original_name: '원본 파일명',
    file_path: '파일 저장 경로',
    file_size: '파일 크기 (bytes)',
    mime_type: 'MIME 타입',
    category: '문서 카테고리 (text/pdf/word/excel/powerpoint/image/other)',
    subcategory: '하위 카테고리',
    tags: '태그 목록 (TEXT[])',
    status: '처리 상태 (uploaded/processing/indexed/vectorizing/vectorized/error)',
    error_message: '에러 메시지 (에러 발생 시)',
    extracted_text: '추출된 텍스트 내용',
    chunk_count: '분할된 청크 수',
    embedding_model: '임베딩에 사용된 모델명',
    description: '문서 설명',
    priority: '처리 우선순위 (low/normal/high)',
    uploaded_by: '업로더 (users.id FK)',
    uploaded_at: '업로드 시각',
    created_at: '레코드 생성 시각',
    updated_at: '레코드 수정 시각',
  },
  rag_models: {
    _table: 'RAG 모델 설정. 문서 기반 AI 모델 구성',
    id: '모델 고유 ID (UUID)',
    name: '모델 고유 이름 (UNIQUE)',
    display_name: '모델 표시 이름',
    description: '모델 설명',
    base_model: '기반 LLM 모델명',
    embedding_model: '임베딩 모델명',
    rag_settings: 'RAG 관련 설정 (JSONB)',
    generation_params: '생성 파라미터 (JSONB). 온도, top_p 등',
    selected_documents: '선택된 문서 ID 배열 (UUID[])',
    document_filters: '문서 필터 조건 (JSONB)',
    status: '모델 상태 (active/inactive/error)',
    is_default: '기본 RAG 모델 여부',
    usage_count: '사용 횟수',
    last_used_at: '마지막 사용 시각',
    created_by: '생성자 (users.id FK)',
    created_at: '생성 시각',
    updated_at: '수정 시각',
    updated_by: '수정자 (users.id FK)',
  },
  rag_settings: {
    _table: 'RAG 전역 설정. 청크 크기, 임베딩, 유사도 등',
    id: '설정 고유 ID (UUID)',
    chunk_size: '문서 분할 청크 크기 (128~4096)',
    chunk_overlap: '청크 간 오버랩 크기 (0~512)',
    embedding_model: '임베딩 모델명. 기본값: nomic-embed-text',
    embedding_dimensions: '임베딩 차원 수. 기본값: 768',
    similarity_top_k: '유사도 검색 상위 K개 (1~10)',
    similarity_threshold: '유사도 임계값 (0.1~1.0)',
    vector_db_path: '벡터 DB 저장 경로',
    table_name: '벡터 DB 테이블명',
    response_mode: '응답 생성 모드 (compact/refine/tree_summarize/simple_summarize)',
    max_tokens: '최대 생성 토큰 수 (256~8192)',
    temperature: '생성 온도 (0.0~2.0)',
    system_prompt: '시스템 프롬프트',
    created_at: '생성 시각',
    updated_at: '수정 시각',
    updated_by: '수정자 (users.id FK)',
  },
  direct_messages: {
    _table: '쪽지 시스템. 사용자 간 1:1 메시지',
    id: '쪽지 고유 ID (UUID)',
    sender_id: '발신자 (users.id FK). 삭제 시 NULL',
    recipient_id: '수신자 (users.id FK). CASCADE 삭제',
    title: '쪽지 제목',
    content: '쪽지 내용',
    is_read: '읽음 여부',
    read_at: '읽은 시각',
    deleted_by_recipient: '수신자가 삭제했는지 여부',
    created_at: '발송 시각',
    updated_at: '수정 시각',
  },
  agent_permissions: {
    _table: '에이전트 접근 권한. 에이전트별 사용 가능 사용자/역할/부서 제어',
    id: '권한 고유 ID (UUID)',
    agent_id: '에이전트 식별자 (예: ppt_maker)',
    permission_type: '권한 유형 (all/role/department/user)',
    permission_value: '권한 값 (역할명/부서명/사용자ID)',
    is_allowed: '허용 여부',
    created_by: '설정자 (users.id FK)',
    created_at: '생성 시각',
    updated_at: '수정 시각',
  },
  agent_settings: {
    _table: '에이전트 설정. PPT 생성기 등 에이전트별 기본 설정',
    id: '설정 고유 ID (UUID)',
    agent_id: '에이전트 식별자 (UNIQUE)',
    selected_model_id: '에이전트가 사용할 모델 ID',
    default_slide_count: 'PPT 기본 슬라이드 수. 기본값: 8',
    default_theme: '기본 테마 (light/dark). 기본값: light',
    default_tone: '기본 톤 (business/casual 등). 기본값: business',
    allow_user_model_override: '사용자 모델 변경 허용 여부',
    is_visible: '에이전트 표시 여부. false면 UI에서 숨김',
    display_order: '에이전트 정렬 순서',
    updated_by: '설정 수정자 (users.id FK)',
    created_at: '생성 시각',
    updated_at: '수정 시각',
  },
  user_settings: {
    _table: '사용자 개인 설정. 모델 선호도 등',
    id: '설정 고유 ID (UUID)',
    user_id: '사용자 (users.id FK). CASCADE 삭제, UNIQUE',
    default_model_id: '사용자가 선호하는 기본 모델 ID',
    created_at: '생성 시각',
    updated_at: '수정 시각',
  },
  user_change_logs: {
    _table: '사용자 정보 변경 이력. SSO 동기화 시 필드 변경 추적',
    id: '이력 고유 ID (BIGSERIAL)',
    user_id: '대상 사용자 UUID',
    employee_no: '사원번호',
    field_name: '변경된 필드명 (예: department, name)',
    old_value: '변경 전 값',
    new_value: '변경 후 값',
    change_type: '변경 유형 (update/create/delete). 기본값: update',
    change_source: '변경 출처 (sso/admin/user). 기본값: sso',
    created_at: '변경 시각',
  },
  app_error_logs: {
    _table: '앱 에러 로그. 서버/클라이언트 에러 수집 및 추적',
    id: '로그 고유 ID (BIGSERIAL)',
    source: '에러 출처 (server/client)',
    level: '에러 레벨 (error/warn/info)',
    message: '에러 메시지',
    stack: '에러 스택트레이스',
    context: '에러 컨텍스트 (JSONB). 추가 디버그 정보',
    user_id: '에러 발생 사용자 UUID',
    user_email: '에러 발생 사용자 이메일',
    request_path: '요청 경로 (예: /api/chat)',
    method: 'HTTP 메서드',
    user_agent: '브라우저 User-Agent',
    created_at: '에러 발생 시각',
  },
  board_posts: {
    _table: '게시판 글. 사용자 게시글 및 공지',
    id: '게시글 고유 ID (BIGSERIAL)',
    user_id: '작성자 UUID',
    title: '글 제목 (최대 200자)',
    content: '글 내용',
    is_notice: '공지 고정 여부',
    views: '조회수',
    created_at: '작성 시각',
    updated_at: '수정 시각',
  },
  board_comments: {
    _table: '게시판 댓글',
    id: '댓글 고유 ID (BIGSERIAL)',
    post_id: '소속 게시글 (board_posts.id FK). CASCADE 삭제',
    user_id: '작성자 UUID',
    content: '댓글 내용',
    created_at: '작성 시각',
    updated_at: '수정 시각',
  },
  sso_login_logs: {
    _table: 'SSO 로그인 이력. SSO 인증 시도 기록',
    id: '로그 고유 ID (UUID)',
    user_id: '사용자 (users.id FK). 삭제 시 NULL',
    employee_no: '사원번호',
    sso_user_id: 'SSO userId',
    auth_type: '인증 타입 (sso)',
    auth_result: '인증 결과 (SUCCESS/FAIL)',
    auth_result_message: '결과 상세 메시지',
    auth_event_id: '인증 이벤트 ID',
    client_ip: '클라이언트 IP',
    user_agent: 'User-Agent',
    created_at: '로그 기록 시각',
  },
  refresh_tokens: {
    _table: '리프레시 토큰. JWT 갱신용 토큰 관리',
    id: '토큰 고유 ID (BIGSERIAL)',
    user_id: '토큰 소유자 (users.id FK). CASCADE 삭제',
    token_hash: '토큰 해시 (UNIQUE)',
    expires_at: '만료 시각',
    revoked: '폐기 여부',
    revoked_at: '폐기 시각',
    created_at: '발급 시각',
    ip_address: '발급 시 IP',
    user_agent: '발급 시 User-Agent',
  },
};

/**
 * 특정 테이블의 특정 컬럼에 대한 설명을 반환합니다.
 * @param {string} tableName - 테이블명
 * @param {string} columnName - 컬럼명
 * @returns {string|null} 컬럼 설명 문자열 또는 null
 */
export function getColumnDescription(tableName, columnName) {
  const table = DB_DESCRIPTIONS[tableName];
  if (!table) return null;
  return table[columnName] || null;
}

/**
 * 특정 테이블의 전체 설명(_table)을 반환합니다.
 * @param {string} tableName - 테이블명
 * @returns {string|null} 테이블 설명 문자열 또는 null
 */
export function getTableDescription(tableName) {
  const table = DB_DESCRIPTIONS[tableName];
  if (!table) return null;
  return table._table || null;
}
