/**
 * Theme preset definitions for hanimo-webui color picker.
 * Each preset defines CSS variable values for light and dark modes.
 * Only primary-family variables are changed — background/neutral colors stay unchanged.
 */

export const THEME_PRESETS = {
  'amber-soft': {
    id: 'amber-soft',
    name: 'Amber Soft',
    nameKo: '앰버 소프트',
    preview: '#e5a63b',
    light: {
      '--primary': '#e5a63b',
      '--primary-foreground': '#ffffff',
      '--ring': '#f5be5b',
      '--chart-1': '#e5a63b',
      '--chart-3': '#f5be5b',
      '--sidebar-primary': '#e5a63b',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-ring': '#f5be5b',
    },
    dark: {
      '--primary': '#f5be5b',
      '--primary-foreground': '#1c1917',
      '--ring': '#fcd480',
      '--chart-1': '#f5be5b',
      '--chart-3': '#fcd480',
      '--sidebar-primary': '#f5be5b',
      '--sidebar-primary-foreground': '#1c1917',
      '--sidebar-ring': '#fcd480',
    },
  },
  blue: {
    id: 'blue',
    name: 'Blue',
    nameKo: '블루',
    preview: '#3b82f6',
    light: {
      '--primary': '#3b82f6',
      '--primary-foreground': '#ffffff',
      '--ring': '#60a5fa',
      '--chart-1': '#3b82f6',
      '--chart-3': '#60a5fa',
      '--sidebar-primary': '#3b82f6',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-ring': '#60a5fa',
    },
    dark: {
      '--primary': '#60a5fa',
      '--primary-foreground': '#0f172a',
      '--ring': '#93c5fd',
      '--chart-1': '#60a5fa',
      '--chart-3': '#93c5fd',
      '--sidebar-primary': '#60a5fa',
      '--sidebar-primary-foreground': '#0f172a',
      '--sidebar-ring': '#93c5fd',
    },
  },
  green: {
    id: 'green',
    name: 'Green',
    nameKo: '그린',
    preview: '#10b981',
    light: {
      '--primary': '#10b981',
      '--primary-foreground': '#ffffff',
      '--ring': '#34d399',
      '--chart-1': '#10b981',
      '--chart-3': '#34d399',
      '--sidebar-primary': '#10b981',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-ring': '#34d399',
    },
    dark: {
      '--primary': '#34d399',
      '--primary-foreground': '#022c22',
      '--ring': '#6ee7b7',
      '--chart-1': '#34d399',
      '--chart-3': '#6ee7b7',
      '--sidebar-primary': '#34d399',
      '--sidebar-primary-foreground': '#022c22',
      '--sidebar-ring': '#6ee7b7',
    },
  },
  purple: {
    id: 'purple',
    name: 'Purple',
    nameKo: '퍼플',
    preview: '#8b5cf6',
    light: {
      '--primary': '#8b5cf6',
      '--primary-foreground': '#ffffff',
      '--ring': '#a78bfa',
      '--chart-1': '#8b5cf6',
      '--chart-3': '#a78bfa',
      '--sidebar-primary': '#8b5cf6',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-ring': '#a78bfa',
    },
    dark: {
      '--primary': '#a78bfa',
      '--primary-foreground': '#1e0a3c',
      '--ring': '#c4b5fd',
      '--chart-1': '#a78bfa',
      '--chart-3': '#c4b5fd',
      '--sidebar-primary': '#a78bfa',
      '--sidebar-primary-foreground': '#1e0a3c',
      '--sidebar-ring': '#c4b5fd',
    },
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    nameKo: '로즈',
    preview: '#f43f5e',
    light: {
      '--primary': '#f43f5e',
      '--primary-foreground': '#ffffff',
      '--ring': '#fb7185',
      '--chart-1': '#f43f5e',
      '--chart-3': '#fb7185',
      '--sidebar-primary': '#f43f5e',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-ring': '#fb7185',
    },
    dark: {
      '--primary': '#fb7185',
      '--primary-foreground': '#1c0a0e',
      '--ring': '#fda4af',
      '--chart-1': '#fb7185',
      '--chart-3': '#fda4af',
      '--sidebar-primary': '#fb7185',
      '--sidebar-primary-foreground': '#1c0a0e',
      '--sidebar-ring': '#fda4af',
    },
  },
  slate: {
    id: 'slate',
    name: 'Slate',
    nameKo: '슬레이트',
    preview: '#64748b',
    light: {
      '--primary': '#64748b',
      '--primary-foreground': '#ffffff',
      '--ring': '#94a3b8',
      '--chart-1': '#64748b',
      '--chart-3': '#94a3b8',
      '--sidebar-primary': '#64748b',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-ring': '#94a3b8',
    },
    dark: {
      '--primary': '#94a3b8',
      '--primary-foreground': '#0f172a',
      '--ring': '#cbd5e1',
      '--chart-1': '#94a3b8',
      '--chart-3': '#cbd5e1',
      '--sidebar-primary': '#94a3b8',
      '--sidebar-primary-foreground': '#0f172a',
      '--sidebar-ring': '#cbd5e1',
    },
  },
};

export const DEFAULT_THEME_PRESET = 'amber-soft';
export const ALLOWED_THEME_VARS = [
  '--primary',
  '--primary-foreground',
  '--ring',
  '--chart-1',
  '--chart-2',
  '--chart-3',
  '--chart-4',
  '--chart-5',
  '--sidebar-primary',
  '--sidebar-primary-foreground',
  '--sidebar-ring',
];
